name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build and run Docker Compose
        run: docker-compose up -d

      - name: Wait for services to be ready
        run: sleep 30 # Adjust time as necessary

      - name: Install PHP and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget php php-cli php-mbstring unzip

      - name: Install PHPUnit
        run: |
          wget -O phpunit https://phar.phpunit.de/phpunit-9.phar
          chmod +x phpunit
          sudo mv phpunit /usr/local/bin/

      - name: Verify test directory exists
        run: |
          if [ ! -d "./wp-content/plugins/woocommerce/tests" ]; then
            echo "Tests directory not found!"
            exit 1
          fi

      - name: Run unit tests
        working-directory: ./wp-content/plugins/woocommerce
        run: phpunit --bootstrap tests/bootstrap.php tests

      - run: echo "TODAY=$(date +%y-%m-%d)" >> $GITHUB_ENV

      - run: echo Hello world, today is $TODAY

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
