name: PHP Composer

on:
  push:
    branches: [ "main" ]
 

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Docker
      uses: docker/setup-buildx-action@v1
    - name: Build and run Docker Compose
      run: docker-compose up -d  
      - name: Wait for services to be ready
      run: sleep 30  # Adjust time as necessary  
    - name: Install PHPUnit
      run: |
        wget -O phpunit https://phar.phpunit.de/phpunit-9.phar
        chmod +x phpunit
        mv phpunit /usr/local/bin/
        - name: Verify test directory exists
     
    - run: echo "TODAY=$(date +%y-%m-%d)" >> $GITHUB_ENV
    - run: echo Hello world, today is $TODAY

  

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
